
var React = require('react');
var ReactDOM = require('react-dom');
var Qt = require('./qt/qt.jsx');
var vgyatnsmhe = Qt.JSArrayModel([], []);
var vgyatnsmhe_selection = Qt.QItemSelectionModel(vgyatnsmhe);
var xtogijcsvu = Qt.JSArrayModel([{'column-0': {'DisplayRole': 'work', 'DecorationRole': 'icons/1365799600128.png'}, 'children': [{'column-0': {'DisplayRole': 'README.txt', 'DecorationRole': 'icons/2469606195200.png'}}]}], [{'name': 'column-0', 'display': 'column-0'}]);
var xtogijcsvu_selection = Qt.QItemSelectionModel(xtogijcsvu);
var galdskrpmx = Qt.JSArrayModel([{'column-0': {'DisplayRole': 'Bookmarks', 'DecorationRole': ''}}, {'column-0': {'DisplayRole': 'Latest Files', 'DecorationRole': ''}, 'children': [{'column-0': {'DisplayRole': '', 'DecorationRole': ''}}]}], [{'name': 'column-0', 'display': 'column-0'}]);
var galdskrpmx_selection = Qt.QItemSelectionModel(galdskrpmx);
var svcpjnhimr = Qt.JSArrayModel([], [{'name': 'column-0', 'display': 'column-0'}, {'name': 'column-1', 'display': 'column-1'}, {'name': 'column-2', 'display': 'column-2'}, {'name': 'column-3', 'display': 'column-3'}, {'name': 'column-4', 'display': 'column-4'}, {'name': 'column-5', 'display': 'column-5'}, {'name': 'column-6', 'display': 'column-6'}]);
var svcpjnhimr_selection = Qt.QItemSelectionModel(svcpjnhimr);
var thnuvmbojc = Qt.JSArrayModel([{'column-1': {'DisplayRole': '', 'DecorationRole': ''}, 'column-0': {'DisplayRole': 'DASHBOARD', 'DecorationRole': ''}, 'column-2': {'DisplayRole': '', 'DecorationRole': ''}}, {'column-1': {'DisplayRole': '', 'DecorationRole': ''}, 'column-0': {'DisplayRole': 'GLOBAL VIEWS', 'DecorationRole': ''}, 'column-2': {'DisplayRole': '', 'DecorationRole': ''}}], [{'name': 'column-0', 'display': 'column-0'}, {'name': 'column-1', 'display': 'column-1'}, {'name': 'column-2', 'display': 'column-2'}]);
var thnuvmbojc_selection = Qt.QItemSelectionModel(thnuvmbojc);
var ofvjbcenqr = Qt.JSArrayModel([{'column-0': {'DisplayRole': 'Comment', 'DecorationRole': ''}, 'children': [{'column-0': {'DisplayRole': 'author (Link)', 'DecorationRole': ''}}, {'column-0': {'DisplayRole': 'comments (List)', 'DecorationRole': ''}}, {'column-0': {'DisplayRole': 'creation time (DateTime)', 'DecorationRole': ''}}, {'column-0': {'DisplayRole': 'description (String)', 'DecorationRole': ''}}, {'column-0': {'DisplayRole': 'image (Image)', 'DecorationRole': ''}}, {'column-0': {'DisplayRole': 'name (String)', 'DecorationRole': ''}}, {'column-0': {'DisplayRole': 'object (Link)', 'DecorationRole': ''}}, {'column-0': {'DisplayRole': 'parent (Link)', 'DecorationRole': ''}}, {'column-0': {'DisplayRole': 'read (List)', 'DecorationRole': ''}}]}, {'column-0': {'DisplayRole': 'User', 'DecorationRole': ''}, 'children': [{'column-0': {'DisplayRole': 'comments (List)', 'DecorationRole': ''}}, {'column-0': {'DisplayRole': 'creation time (DateTime)', 'DecorationRole': ''}}, {'column-0': {'DisplayRole': 'description (String)', 'DecorationRole': ''}}, {'column-0': {'DisplayRole': 'image (Image)', 'DecorationRole': ''}}, {'column-0': {'DisplayRole': 'login (String)', 'DecorationRole': ''}}, {'column-0': {'DisplayRole': 'name (String)', 'DecorationRole': ''}}]}, {'column-0': {'DisplayRole': 'UserGroup', 'DecorationRole': ''}, 'children': [{'column-0': {'DisplayRole': 'comments (List)', 'DecorationRole': ''}}, {'column-0': {'DisplayRole': 'creation time (DateTime)', 'DecorationRole': ''}}, {'column-0': {'DisplayRole': 'description (String)', 'DecorationRole': ''}}, {'column-0': {'DisplayRole': 'image (Image)', 'DecorationRole': ''}}, {'column-0': {'DisplayRole': 'name (String)', 'DecorationRole': ''}}]}], [{'name': 'column-0', 'display': 'column-0'}]);
var ofvjbcenqr_selection = Qt.QItemSelectionModel(ofvjbcenqr);
ReactDOM.render(
<Qt.QApplication doubleClickInterval="400" startDragDistance="4" wheelScrollLines="3" autoSipEnabled="true" windowIcon="" cursorFlashTime="1000" quitOnLastWindowClosed="true" id="build_vortex_source.py" applicationVersion="" applicationName="Vortex Detal" organizationName="Hydralab" layoutDirection="0" keyboardInputInterval="400" startDragTime="500" organizationDomain="hydralab.com" globalStrut="">
    <Qt.QMainWindow dockNestingEnabled="false" contextMenuPolicy="1" locale="" minimumSize="" windowModified="false" pos="" mouseTracking="false" minimumHeight="302" baseSize="" id="" size="" autoFillBackground="false" whatsThis="" palette="" windowTitle="Vortex   - NOT LOGGED IN" layoutDirection="0" accessibleName="" sizeIncrement="" windowModality="0" tabShape="0" width="1040" windowIconText="" documentMode="false" statusTip="" sizePolicy="" minimumWidth="581" unifiedTitleAndToolBarOnMac="false" iconSize="" maximumHeight="16777215" acceptDrops="false" toolTip="" windowFilePath="" windowIcon="" height="577" maximumWidth="16777215" inputMethodHints="0" geometry="" dockOptions="9" enabled="true" focusPolicy="0" windowOpacity="1" updatesEnabled="true" cursor="" toolButtonStyle="0" accessibleDescription="" animated="true" maximumSize="">
        <Qt.QHBoxLayout qt-ref="centralWidget" margin="0" spacing="0" sizeConstraint="0" id="">
            <Qt.QVBoxLayout margin="2" spacing="2" sizeConstraint="0" id="">
                <Qt.QLabel contextMenuPolicy="1" scaledContents="false" locale="" text="" pos="" mouseTracking="false" midLineWidth="0" cursor="" wordWrap="false" minimumHeight="0" baseSize="" id="VXOverlayVerticalLabel" alignment="129" size="" autoFillBackground="false" pixmap="" palette="" windowTitle="" layoutDirection="0" accessibleName="" sizeIncrement="" windowModality="0" whatsThis="" width="0" windowIconText="" textInteractionFlags="4" sizePolicy="" minimumWidth="0" windowModified="false" statusTip="" maximumHeight="16777215" acceptDrops="false" toolTip="" windowFilePath="" minimumSize="" windowIcon="" frameShadow="16" height="0" maximumWidth="16777215" inputMethodHints="0" indent="-1" geometry="" openExternalLinks="false" enabled="true" focusPolicy="0" windowOpacity="1" updatesEnabled="true" frameShape="0" accessibleDescription="" textFormat="2" lineWidth="1" margin="0" maximumSize="" frameRect=""></Qt.QLabel>
            </Qt.QVBoxLayout>
            <Qt.QVBoxLayout margin="0" spacing="0" sizeConstraint="0" id="">
                <Qt.QStackedWidget contextMenuPolicy="1" locale="" minimumSize="" pos="" mouseTracking="false" midLineWidth="0" minimumHeight="22" baseSize="" id="pathFrame" size="" autoFillBackground="false" cursor="" palette="" windowTitle="" layoutDirection="0" accessibleName="" sizeIncrement="" windowModality="0" whatsThis="" width="0" windowIconText="" accessibleDescription="" sizePolicy="" minimumWidth="0" windowModified="false" statusTip="" maximumHeight="20" acceptDrops="false" toolTip="" windowFilePath="" windowIcon="" frameShadow="16" height="16" maximumWidth="16777215" inputMethodHints="0" geometry="" frameRect="" enabled="true" focusPolicy="0" windowOpacity="1" updatesEnabled="true" frameShape="0" currentIndex="0" lineWidth="1" maximumSize="">
                    <Qt.QStackedLayout sizeConstraint="0" currentIndex="0" margin="9" spacing="6" id="" stackingMode="0">
                        <Qt.QHBoxLayout margin="0" spacing="0" sizeConstraint="0" id="">
                            <Qt.QListWidget contextMenuPolicy="1" horizontalScrollBarPolicy="1" pos="" mouseTracking="false" frameShadow="48" minimumHeight="0" showDropIndicator="true" selectionRectVisible="false" size="" autoFillBackground="false" isWrapping="false" layoutDirection="0" width="0" batchSize="100" sizeIncrement="" whatsThis="" accessibleName="" dragDropMode="0" horizontalScrollMode="0" sizePolicy="" windowModified="false" statusTip="" acceptDrops="false" sortingEnabled="false" inputMethodHints="0" editTriggers="10" dragDropOverwriteMode="false" selectionMode="1" height="16" textElideMode="1" currentRow="-1" tabKeyNavigation="false" verticalScrollBarPolicy="1" windowIconText="" enabled="true" focusPolicy="15" dragEnabled="false" updatesEnabled="true" cursor="" gridSize="" maximumSize="" frameRect="" verticalScrollMode="0" locale="" minimumSize="" windowFilePath="" midLineWidth="0" defaultDropAction="0" wordWrap="false" baseSize="" id="PathBarListWidget" palette="" resizeMode="0" windowTitle="" selectionModel={vgyatnsmhe_selection} windowModality="0" movement="0" autoScrollMargin="16" minimumWidth="0" iconSize="" alternatingRowColors="false" maximumHeight="16777215" spacing="0" toolTip="" windowIcon="" autoScroll="true" layoutMode="0" maximumWidth="16777215" geometry="" flow="0" uniformItemSizes="false" windowOpacity="1" frameShape="6" viewMode="0" accessibleDescription="" selectionBehavior="0" model={vgyatnsmhe} lineWidth="1" modelColumn="0"></Qt.QListWidget>
                        </Qt.QHBoxLayout>
                        <Qt.QHBoxLayout margin="0" spacing="0" sizeConstraint="0" id="">
                            <Qt.QLineEdit echoMode="0" contextMenuPolicy="1" locale="" text="" frame="true" pos="" mouseTracking="true" windowOpacity="1" minimumHeight="0" updatesEnabled="true" baseSize="" id="pathLine" alignment="129" size="" autoFillBackground="false" cursorPosition="0" palette="" windowTitle="" layoutDirection="0" accessibleName="" sizeIncrement="" windowModality="0" whatsThis="" width="0" windowIconText="" sizePolicy="" minimumWidth="0" windowModified="false" statusTip="" maximumHeight="16777215" acceptDrops="true" toolTip="" windowFilePath="" minimumSize="" readOnly="false" windowIcon="" maxLength="32767" height="22" inputMask="" maximumWidth="16777215" inputMethodHints="0" geometry="" enabled="true" modified="false" dragEnabled="false" cursorMoveStyle="0" cursor="" accessibleDescription="" placeholderText="" maximumSize="" focusPolicy="2"></Qt.QLineEdit>
                        </Qt.QHBoxLayout>
                    </Qt.QStackedLayout>
                </Qt.QStackedWidget>
                <Qt.QColumnView contextMenuPolicy="3" horizontalScrollBarPolicy="0" pos="" mouseTracking="false" frameShadow="48" minimumHeight="0" showDropIndicator="true" size="" autoFillBackground="false" layoutDirection="0" width="0" resizeGripsVisible="true" sizeIncrement="" whatsThis="" accessibleName="" dragDropMode="1" horizontalScrollMode="0" sizePolicy="" windowModified="false" statusTip="" acceptDrops="false" editTriggers="10" dragDropOverwriteMode="false" selectionMode="4" height="289" textElideMode="2" inputMethodHints="0" tabKeyNavigation="false" verticalScrollBarPolicy="0" windowIconText="" enabled="true" focusPolicy="11" dragEnabled="true" updatesEnabled="true" cursor="" maximumSize="" frameRect="" verticalScrollMode="0" locale="" minimumSize="" windowFilePath="" midLineWidth="0" defaultDropAction="0" baseSize="" id="FileColumnView" palette="" windowTitle="" selectionModel={xtogijcsvu_selection} windowModality="0" autoScrollMargin="16" minimumWidth="0" iconSize="" alternatingRowColors="false" maximumHeight="16777215" toolTip="" windowIcon="" autoScroll="true" maximumWidth="16777215" geometry="" windowOpacity="1" frameShape="6" accessibleDescription="" selectionBehavior="0" model={xtogijcsvu} lineWidth="1"></Qt.QColumnView>
            </Qt.QVBoxLayout>
        </Qt.QHBoxLayout>
        <Qt.QMenuBar qt-ref="menuBar" contextMenuPolicy="1" locale="" minimumSize="" pos="" mouseTracking="true" windowOpacity="1" minimumHeight="0" baseSize="" id="VXMainMenubar" size="" autoFillBackground="false" palette="" windowTitle="" layoutDirection="0" accessibleName="" sizeIncrement="" windowModality="0" whatsThis="" width="0" windowIconText="" sizePolicy="" minimumWidth="0" windowModified="false" statusTip="" maximumHeight="16777215" acceptDrops="false" toolTip="" windowFilePath="" windowIcon="" height="0" maximumWidth="16777215" inputMethodHints="0" geometry="" enabled="true" focusPolicy="0" nativeMenuBar="true" updatesEnabled="true" cursor="" defaultUp="false" accessibleDescription="" maximumSize="">
            <Qt.QMenu contextMenuPolicy="1" locale="" minimumSize="" pos="" mouseTracking="true" minimumHeight="0" baseSize="" id="" size="" autoFillBackground="false" palette="" windowTitle="" layoutDirection="0" title="File" sizeIncrement="" windowModality="0" whatsThis="" accessibleName="" windowIconText="" sizePolicy="" minimumWidth="0" windowModified="false" statusTip="" maximumHeight="16777215" acceptDrops="false" toolTip="" windowFilePath="" windowIcon="" tearOffEnabled="false" height="22" icon="" maximumWidth="16777215" inputMethodHints="0" geometry="" enabled="true" focusPolicy="0" windowOpacity="1" updatesEnabled="true" cursor="" accessibleDescription="" separatorsCollapsible="true" width="0" maximumSize="">
                <Qt.QAction statusTip="" text="Create Project" softKeyRole="0" iconText="Create Project" toolTip="Create Project" isSeparator="0" checkable="false" id="CreateProjectAction" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
                <Qt.QAction statusTip="Exits the application" text="Shutdown" softKeyRole="0" iconText="Shutdown" toolTip="Shutdown" isSeparator="0" checkable="false" id="VX_Shutdown_Action" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="Ctrl+Q" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
                <Qt.QAction statusTip="" text="Settings" softKeyRole="0" iconText="Settings" toolTip="Settings" isSeparator="0" checkable="false" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="5" priority="128"></Qt.QAction>
            </Qt.QMenu>
            <Qt.QMenu contextMenuPolicy="1" locale="" minimumSize="" pos="" mouseTracking="true" minimumHeight="0" baseSize="" id="VXShowMenu" size="" autoFillBackground="false" palette="" windowTitle="" layoutDirection="0" title="Show" sizeIncrement="" windowModality="0" whatsThis="" accessibleName="" windowIconText="" sizePolicy="" minimumWidth="0" windowModified="false" statusTip="" maximumHeight="16777215" acceptDrops="false" toolTip="" windowFilePath="" windowIcon="" tearOffEnabled="false" height="22" icon="" maximumWidth="16777215" inputMethodHints="0" geometry="" enabled="true" focusPolicy="0" windowOpacity="1" updatesEnabled="true" cursor="" accessibleDescription="" separatorsCollapsible="true" width="0" maximumSize="">
                <Qt.QAction statusTip="" text="Windows" softKeyRole="0" iconText="Windows" toolTip="Windows" isSeparator="1" checkable="false" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="false" shortcut="" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
                <Qt.QAction statusTip="" text="Vortex Control" softKeyRole="0" iconText="Vortex Control" toolTip="Vortex Control" isSeparator="0" checkable="true" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="0" priority="128"></Qt.QAction>
                <Qt.QAction statusTip="" text="Detail Window" softKeyRole="0" iconText="Detail Window" toolTip="Detail Window" isSeparator="0" checkable="true" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="0" priority="128"></Qt.QAction>
                <Qt.QAction statusTip="" text="Toolbars" softKeyRole="0" iconText="Toolbars" toolTip="Toolbars" isSeparator="1" checkable="false" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
                <Qt.QAction statusTip="" text="Control Toolbar" softKeyRole="0" iconText="Control Toolbar" toolTip="Control Toolbar" isSeparator="0" checkable="true" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="0" priority="128"></Qt.QAction>
                <Qt.QAction statusTip="" text="Revision Toolbar" softKeyRole="0" iconText="Revision Toolbar" toolTip="Revision Toolbar" isSeparator="0" checkable="true" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="0" priority="128"></Qt.QAction>
                <Qt.QAction statusTip="" text="Projects Toolbar" softKeyRole="0" iconText="Projects Toolbar" toolTip="Projects Toolbar" isSeparator="0" checkable="true" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="0" priority="128"></Qt.QAction>
                <Qt.QAction statusTip="" text="Login Toolbar" softKeyRole="0" iconText="Login Toolbar" toolTip="Login Toolbar" isSeparator="0" checkable="true" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="0" priority="128"></Qt.QAction>
                <Qt.QAction statusTip="" text="Main Toolbar" softKeyRole="0" iconText="Main Toolbar" toolTip="Main Toolbar" isSeparator="0" checkable="true" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="0" priority="128"></Qt.QAction>
                <Qt.QAction statusTip="" text="Views" softKeyRole="0" iconText="Views" toolTip="Views" isSeparator="1" checkable="false" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
                <Qt.QAction statusTip="" text="File browser" softKeyRole="0" iconText="File browser" toolTip="File browser" isSeparator="0" checkable="true" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="0" priority="128"></Qt.QAction>
                <Qt.QAction statusTip="" text="Templates" softKeyRole="0" iconText="Templates" toolTip="Templates" isSeparator="0" checkable="true" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="0" priority="128"></Qt.QAction>
                <Qt.QAction statusTip="" text="Types" softKeyRole="0" iconText="Types" toolTip="Types" isSeparator="0" checkable="true" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="0" priority="128"></Qt.QAction>
                <Qt.QAction statusTip="" text="Data View Tear" softKeyRole="0" iconText="Data View Tear" toolTip="Data View Tear" isSeparator="0" checkable="true" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="0" priority="128"></Qt.QAction>
                <Qt.QAction statusTip="" text="Shortcuts" softKeyRole="0" iconText="Shortcuts" toolTip="Shortcuts" isSeparator="0" checkable="true" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="0" priority="128"></Qt.QAction>
                <Qt.QAction statusTip="" text="Script Editor" softKeyRole="0" iconText="Script Editor" toolTip="Script Editor" isSeparator="0" checkable="true" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="0" priority="128"></Qt.QAction>
                <Qt.QAction statusTip="" text="Settings Editor" softKeyRole="0" iconText="Settings Editor" toolTip="Settings Editor" isSeparator="0" checkable="true" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="0" priority="128"></Qt.QAction>
                <Qt.QAction statusTip="" text="Revision" softKeyRole="0" iconText="Revision" toolTip="Revision" isSeparator="0" checkable="true" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="0" priority="128"></Qt.QAction>
            </Qt.QMenu>
            <Qt.QMenu contextMenuPolicy="1" locale="" minimumSize="" pos="" mouseTracking="true" minimumHeight="0" baseSize="" id="" size="" autoFillBackground="false" palette="" windowTitle="" layoutDirection="0" title="Settings" sizeIncrement="" windowModality="0" whatsThis="" accessibleName="" windowIconText="" sizePolicy="" minimumWidth="0" windowModified="false" statusTip="" maximumHeight="16777215" acceptDrops="false" toolTip="" windowFilePath="" windowIcon="" tearOffEnabled="false" height="22" icon="" maximumWidth="16777215" inputMethodHints="0" geometry="" enabled="true" focusPolicy="0" windowOpacity="1" updatesEnabled="true" cursor="" accessibleDescription="" separatorsCollapsible="true" width="0" maximumSize="">
                <Qt.QAction statusTip="Reload all extensions" text="Reload Extensions" softKeyRole="0" iconText="Reload Extensions" toolTip="Reload Extensions" isSeparator="0" checkable="false" id="Reload Extensions" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
                <Qt.QAction statusTip="" text="Reload Settings" softKeyRole="0" iconText="Reload Settings" toolTip="Reload Settings" isSeparator="0" checkable="false" id="Reload Settings" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
                <Qt.QAction statusTip="" text="Reload Style Sheet" softKeyRole="0" iconText="Reload Style Sheet" toolTip="Reload Style Sheet" isSeparator="0" checkable="false" id="Reload Stylesheet" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
                <Qt.QAction statusTip="" text="" softKeyRole="0" iconText="" toolTip="" isSeparator="1" checkable="false" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
                <Qt.QAction statusTip="" text="Sequence Mode" softKeyRole="0" iconText="Sequence Mode" toolTip="Sequence Mode" isSeparator="0" checkable="true" id="Toggle Seq Mode" icon="" whatsThis="" iconVisibleInMenu="false" checked="true" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
            </Qt.QMenu>
            <Qt.QMenu contextMenuPolicy="1" locale="" minimumSize="" pos="" mouseTracking="true" minimumHeight="0" baseSize="" id="" size="" autoFillBackground="false" palette="" windowTitle="" layoutDirection="0" title="Tools" sizeIncrement="" windowModality="0" whatsThis="" accessibleName="" windowIconText="" sizePolicy="" minimumWidth="0" windowModified="false" statusTip="" maximumHeight="16777215" acceptDrops="false" toolTip="" windowFilePath="" windowIcon="" tearOffEnabled="false" height="22" icon="" maximumWidth="16777215" inputMethodHints="0" geometry="" enabled="true" focusPolicy="0" windowOpacity="1" updatesEnabled="true" cursor="" accessibleDescription="" separatorsCollapsible="true" width="0" maximumSize="">
                <Qt.QAction statusTip="Make the end-of-line character consistent to the whole file" text="EOL File Fix" softKeyRole="0" iconText="EOL File Fix" toolTip="EOL File Fix" isSeparator="0" checkable="false" id="Fix EOL Action" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
            </Qt.QMenu>
            <Qt.QMenu contextMenuPolicy="1" locale="" minimumSize="" pos="" mouseTracking="true" minimumHeight="0" baseSize="" id="VXHelpMenu" size="" autoFillBackground="false" palette="" windowTitle="" layoutDirection="0" title="Help" sizeIncrement="" windowModality="0" whatsThis="" accessibleName="" windowIconText="" sizePolicy="" minimumWidth="0" windowModified="false" statusTip="" maximumHeight="16777215" acceptDrops="false" toolTip="" windowFilePath="" windowIcon="" tearOffEnabled="false" height="22" icon="" maximumWidth="16777215" inputMethodHints="0" geometry="" enabled="true" focusPolicy="0" windowOpacity="1" updatesEnabled="true" cursor="" accessibleDescription="" separatorsCollapsible="true" width="0" maximumSize="">
                <Qt.QAction statusTip="Open help documentation for API" text="API Documentation" softKeyRole="0" iconText="API Documentation" toolTip="API Documentation" isSeparator="0" checkable="false" id="open API Documentation" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
                <Qt.QAction statusTip="" text="About" softKeyRole="0" iconText="About" toolTip="About" isSeparator="0" checkable="false" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="4" priority="128"></Qt.QAction>
            </Qt.QMenu>
        </Qt.QMenuBar>
        <Qt.QToolBar floatable="false" orientation="1" locale="" minimumSize="" pos="" mouseTracking="false" minimumHeight="0" baseSize="" id="BookmarkBar" size="" autoFillBackground="false" contextMenuPolicy="1" palette="" windowTitle="Projects Toolbar" layoutDirection="0" accessibleName="" sizeIncrement="" windowModality="0" whatsThis="" width="333" windowIconText="" statusTip="" sizePolicy="" minimumWidth="0" windowModified="false" iconSize="" maximumHeight="16777215" movable="false" toolTip="" acceptDrops="false" windowIcon="" height="50" windowFilePath="" maximumWidth="16777215" inputMethodHints="0" allowedAreas="15" geometry="" area="4" enabled="true" focusPolicy="0" windowOpacity="1" updatesEnabled="true" cursor="" toolButtonStyle="0" accessibleDescription="" maximumSize="">
            <Qt.QAction statusTip="Select your Project here" text="my test project | Test Component" softKeyRole="0" iconText="my test project | Test Component" toolTip="my test project | Test Component" isSeparator="0" checkable="false" id="Show Projects" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
        </Qt.QToolBar>
        <Qt.QToolBar floatable="true" orientation="1" locale="" minimumSize="" pos="" mouseTracking="false" minimumHeight="0" baseSize="" id="LoginBar" size="" autoFillBackground="false" contextMenuPolicy="1" palette="" windowTitle="Login Toolbar" layoutDirection="0" accessibleName="" sizeIncrement="" windowModality="0" whatsThis="" width="244" windowIconText="" statusTip="" sizePolicy="" minimumWidth="0" windowModified="false" iconSize="" maximumHeight="16777215" movable="false" toolTip="" acceptDrops="false" windowIcon="" height="50" windowFilePath="" maximumWidth="16777215" inputMethodHints="0" allowedAreas="15" geometry="" area="4" enabled="true" focusPolicy="0" windowOpacity="1" updatesEnabled="true" cursor="" toolButtonStyle="3" accessibleDescription="" maximumSize="">
            <Qt.QAction statusTip="Login to Vortex Control" text="Login" softKeyRole="0" iconText="LOGIN" toolTip="Login" isSeparator="0" checkable="false" id="Login" icon="icons/957777707008.png" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="Ctrl+L" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
            <Qt.QAction statusTip="Open the Control Interface" text="Control" softKeyRole="0" iconText="CONTROL" toolTip="Control" isSeparator="0" checkable="false" id="Control" icon="icons/970662608896.png" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="Ctrl+Alt+C" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
            <Qt.QAction statusTip="" text="QUEUE" softKeyRole="0" iconText="QUEUE" toolTip="QUEUE" isSeparator="0" checkable="false" id="VX_Show_Queue_Control_Action" icon="icons/983547510784.png" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="Ctrl+J" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
        </Qt.QToolBar>
        <Qt.QToolBar floatable="true" orientation="1" locale="" minimumSize="" pos="" mouseTracking="false" minimumHeight="0" baseSize="" id="RevisionBar" size="" autoFillBackground="false" contextMenuPolicy="1" palette="" windowTitle="Main Toolbar" layoutDirection="0" accessibleName="" sizeIncrement="" windowModality="0" whatsThis="" width="462" windowIconText="" statusTip="" sizePolicy="" minimumWidth="0" windowModified="false" iconSize="" maximumHeight="16777215" movable="false" toolTip="" acceptDrops="false" windowIcon="" height="50" windowFilePath="" maximumWidth="16777215" inputMethodHints="0" allowedAreas="15" geometry="" area="4" enabled="true" focusPolicy="0" windowOpacity="1" updatesEnabled="true" cursor="" toolButtonStyle="3" accessibleDescription="" maximumSize="">
            <Qt.QAction statusTip="" text="" softKeyRole="0" iconText="" toolTip="" isSeparator="1" checkable="false" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
            <Qt.QAction statusTip="Commit the selected file to its repository" text="Commit" softKeyRole="0" iconText="COMMIT" toolTip="Commit" isSeparator="0" checkable="false" id="Commit" icon="icons/1005022347264.png" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
            <Qt.QAction statusTip="" text="" softKeyRole="0" iconText="" toolTip="" isSeparator="1" checkable="false" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
            <Qt.QAction statusTip="Refresh the browser" text="Refresh" softKeyRole="0" iconText="REFRESH" toolTip="Refresh" isSeparator="0" checkable="false" id="RefreshBrowser" icon="icons/1017907249152.png" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
        </Qt.QToolBar>
        <Qt.QDockWidget contextMenuPolicy="1" features="0" locale="" minimumSize="" pos="" mouseTracking="true" minimumHeight="71" floating="false" baseSize="" id="ShortcutDock" size="" autoFillBackground="false" palette="" windowTitle="Shortcuts" layoutDirection="0" accessibleName="" sizeIncrement="" windowModality="0" whatsThis="" width="74" windowIconText="" sizePolicy="" minimumWidth="100" windowModified="false" statusTip="" maximumHeight="524287" acceptDrops="false" toolTip="" windowFilePath="" windowIcon="" height="500" maximumWidth="524287" inputMethodHints="0" allowedAreas="1" geometry="" area="1" enabled="true" focusPolicy="0" windowOpacity="1" updatesEnabled="true" cursor="" accessibleDescription="" maximumSize="">
            <Qt.QTreeWidget contextMenuPolicy="1" horizontalScrollBarPolicy="0" autoExpandDelay="-1" height="500" frameShadow="48" allColumnsShowFocus="false" minimumHeight="0" showDropIndicator="true" size="" autoFillBackground="false" layoutDirection="0" width="0" sizeIncrement="" whatsThis="" accessibleName="" dragDropMode="3" expandsOnDoubleClick="true" horizontalScrollMode="1" sizePolicy="" windowModified="false" statusTip="" acceptDrops="true" pos="" sortingEnabled="false" editTriggers="10" dragDropOverwriteMode="false" selectionMode="1" mouseTracking="false" textElideMode="1" inputMethodHints="0" tabKeyNavigation="false" verticalScrollBarPolicy="0" headerHidden="true" windowIconText="" enabled="true" focusPolicy="15" dragEnabled="true" updatesEnabled="true" cursor="" animated="false" maximumSize="" frameRect="" columnCount="1" verticalScrollMode="0" locale="" rootIsDecorated="true" windowFilePath="" midLineWidth="0" defaultDropAction="0" wordWrap="false" baseSize="" id="ShortcutView" palette="" windowTitle="" selectionModel={galdskrpmx_selection} windowModality="0" autoScrollMargin="16" minimumWidth="100" iconSize="" alternatingRowColors="false" maximumHeight="16777215" toolTip="" minimumSize="" uniformRowHeights="false" windowIcon="" autoScroll="true" itemsExpandable="true" maximumWidth="16777215" geometry="" windowOpacity="1" frameShape="6" accessibleDescription="" indentation="20" selectionBehavior="1" model={galdskrpmx} lineWidth="1"></Qt.QTreeWidget>
        </Qt.QDockWidget>
        <Qt.QDockWidget contextMenuPolicy="1" features="1" locale="" minimumSize="" pos="" mouseTracking="true" minimumHeight="98" floating="false" baseSize="" id="RevisionDock" size="" autoFillBackground="false" palette="" windowTitle="Revision" layoutDirection="0" accessibleName="" sizeIncrement="" windowModality="0" whatsThis="" width="961" windowIconText="" sizePolicy="" minimumWidth="76" windowModified="false" statusTip="" maximumHeight="524287" acceptDrops="false" toolTip="" windowFilePath="" windowIcon="" height="189" maximumWidth="524287" inputMethodHints="0" allowedAreas="8" geometry="" area="8" enabled="true" focusPolicy="0" windowOpacity="1" updatesEnabled="true" cursor="" accessibleDescription="" maximumSize="">
            <Qt.QVBoxLayout margin="0" spacing="0" sizeConstraint="0" id="">
                <Qt.QHBoxLayout margin="0" spacing="0" sizeConstraint="0" id="">
                    <Qt.QToolBar floatable="true" orientation="1" locale="" minimumSize="" pos="" mouseTracking="false" minimumHeight="0" baseSize="" id="RevisionBar" size="" autoFillBackground="false" contextMenuPolicy="1" palette="" windowTitle="Revision Toolbar" layoutDirection="0" accessibleName="" sizeIncrement="" windowModality="0" whatsThis="" width="395" windowIconText="" statusTip="" sizePolicy="" minimumWidth="0" windowModified="false" iconSize="" maximumHeight="16777215" movable="true" toolTip="" acceptDrops="false" windowIcon="" height="32" windowFilePath="" maximumWidth="16777215" inputMethodHints="0" allowedAreas="15" geometry="" enabled="true" focusPolicy="0" windowOpacity="1" updatesEnabled="true" cursor="" toolButtonStyle="2" accessibleDescription="" maximumSize="">
                        <Qt.QAction statusTip="" text="" softKeyRole="0" iconText="" toolTip="" isSeparator="1" checkable="false" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
                        <Qt.QAction statusTip="Revert the selected file to the selected revision" text="Revert" softKeyRole="0" iconText="REVERT" toolTip="Revert" isSeparator="0" checkable="false" id="Revert" icon="icons/858993459200.png" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
                        <Qt.QAction statusTip="" text="" softKeyRole="0" iconText="" toolTip="" isSeparator="1" checkable="false" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
                        <Qt.QAction statusTip="Restore a file from previous version" text="Restore" softKeyRole="0" iconText="RESTORE" toolTip="Restore" isSeparator="0" checkable="false" id="RestoreAction" icon="icons/880468295680.png" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
                        <Qt.QAction statusTip="" text="" softKeyRole="0" iconText="" toolTip="" isSeparator="1" checkable="false" id="" icon="" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
                        <Qt.QAction statusTip="Quick Look the selected revision" text="Quick Look" softKeyRole="0" iconText="QUICK LOOK" toolTip="Quick Look" isSeparator="0" checkable="false" id="QuicklookAction" icon="icons/893353197568.png" whatsThis="" iconVisibleInMenu="false" checked="false" autoRepeat="true" enabled="true" shortcut="" shortcutContext="1" menuRole="1" priority="128"></Qt.QAction>
                    </Qt.QToolBar>
                </Qt.QHBoxLayout>
                <Qt.QTreeView contextMenuPolicy="1" horizontalScrollBarPolicy="0" autoExpandDelay="-1" height="157" frameShadow="48" allColumnsShowFocus="false" minimumHeight="0" showDropIndicator="true" size="" autoFillBackground="false" layoutDirection="0" width="0" sizeIncrement="" whatsThis="" accessibleName="" dragDropMode="0" expandsOnDoubleClick="true" horizontalScrollMode="1" sizePolicy="" windowModified="false" statusTip="" acceptDrops="false" pos="" sortingEnabled="false" editTriggers="10" dragDropOverwriteMode="false" selectionMode="1" mouseTracking="false" textElideMode="1" inputMethodHints="0" tabKeyNavigation="false" verticalScrollBarPolicy="0" headerHidden="false" windowIconText="" enabled="true" focusPolicy="15" dragEnabled="false" updatesEnabled="true" cursor="" animated="false" maximumSize="" frameRect="" verticalScrollMode="1" locale="" rootIsDecorated="true" windowFilePath="" midLineWidth="0" defaultDropAction="0" wordWrap="false" baseSize="" id="FileRevisionTree" palette="" windowTitle="" selectionModel={svcpjnhimr_selection} windowModality="0" autoScrollMargin="16" minimumWidth="0" iconSize="" alternatingRowColors="true" maximumHeight="16777215" toolTip="" minimumSize="" uniformRowHeights="false" windowIcon="" autoScroll="true" itemsExpandable="false" maximumWidth="16777215" geometry="" windowOpacity="1" frameShape="6" accessibleDescription="" indentation="0" selectionBehavior="1" model={svcpjnhimr} lineWidth="1"></Qt.QTreeView>
            </Qt.QVBoxLayout>
        </Qt.QDockWidget>
    </Qt.QMainWindow>
</Qt.QApplication>, document.getElementById("content"));